//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventosGarantia
    {
        public int IdEvento { get; set; }
        public int IdGarantia { get; set; }
        public System.DateTime FechaEvento { get; set; }
        public Nullable<System.DateTime> NuevaFechaFin { get; set; }
        public string DescripcionEvento { get; set; }
    
        public virtual Garantia Garantia { get; set; }
    }
}
