//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garantia
    {
        public int IdGarantia { get; set; }
        public int IdDetalleFacturaVenta { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int Estado { get; set; }
        public string RazonReclamo { get; set; }
        public Nullable<System.DateTime> FechaReclamo { get; set; }
        public Nullable<System.DateTime> FechaEstimadaEntrega { get; set; }
    
        public virtual DetalleFacturaVenta DetalleFacturaVenta { get; set; }
    }
}
