//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleFacturaVenta = new HashSet<DetalleFacturaVenta>();
        }
    
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Modelo { get; set; }
        public string Descripcion { get; set; }
        public int Stock { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal PrecioVenta { get; set; }
        public Nullable<int> Almacenamiento { get; set; }
        public Nullable<int> GarantiaMeses { get; set; }
        public Nullable<int> RAM { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdColor { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<int> EditadoPor { get; set; }
        public Nullable<int> EliminadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public Nullable<int> Bateria { get; set; }
        public Nullable<bool> Nuevo { get; set; }
        public Nullable<bool> eSim { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string IMEI { get; set; }
        public string CodigoBarra { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Color Color { get; set; }
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaVenta> DetalleFacturaVenta { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual ValoresUnidadMedida ValoresUnidadMedida { get; set; }
        public virtual ValoresUnidadMedida ValoresUnidadMedida1 { get; set; }
        public virtual ValoresUnidadMedida ValoresUnidadMedida2 { get; set; }
    }
}
